// ignore_for_file: unused_local_variable, unused_import, unused_element
import 'dart:convert';
import 'dart:ffi';
import 'dart:io' as io;
import 'dart:math';

import 'knock00.dart';
import 'knock01.dart';
import 'knock02.dart';
import 'knock03.dart';
import 'knock04.dart';
import 'knock05.dart';
import 'knock06.dart';
import 'knock07.dart';
import 'knock08.dart';
import 'knock09.dart';
import 'knock10.dart';
import 'knock11.dart';
import 'knock12.dart';
import 'knock13.dart';
import 'knock14.dart';
import 'knock15.dart';
import 'knock16.dart';
import 'knock17.dart';
import 'knock18.dart';
import 'knock19.dart';
import 'knock20.dart';
import 'knock21.dart';
import 'knock22.dart';
import 'knock23.dart';
import 'knock24.dart';
import 'knock25.dart';
import 'knock26.dart';
import 'knock27.dart';
import 'knock28.dart';
import 'knock29.dart';
import 'knock30.dart';
import 'knock31.dart';
import 'knock32.dart';
import 'knock33.dart';
import 'knock34.dart';
import 'knock35.dart';
import 'knock36.dart';
import 'knock37.dart';
import 'knock38.dart';
import 'knock39.dart';
import 'knock40.dart';
import 'knock41.dart';
import 'knock42.dart';
import 'knock43.dart';
import 'knock44.dart';
import 'knock45.dart';
import 'knock46.dart';
import 'knock47.dart';
import 'knock48.dart';
import 'knock49.dart';
import 'knock50.dart';
import 'knock51.dart';
import 'knock52.dart';
import 'knock53.dart';

void main() {
  print('input question number : ');
  var question = io.stdin.readLineSync();
  num qNum = int.parse(question!);
  switch (qNum) {
    case 0:
      return (Knock00());
    case 1:
      return (Knock01());
    case 2:
      return (Knock02());
    case 3:
      return (Knock03());
    case 4:
      return (Knock04());
    case 5:
      return (Knock05());
    case 6:
      return (Knock06());
    case 7:
      return (Knock07());
    case 8:
      return (Knock08());
    case 9:
      return (Knock09());
    case 10:
      return (Knock10());
    case 11:
      return (Knock11());
    case 12:
      return (Knock12());
    case 13:
      return (Knock13());
    case 14:
      return (Knock14());
    case 15:
      return (Knock15());
    case 16:
      return (Knock16());
    case 17:
      return (Knock17());
    case 18:
      return (Knock18());
    case 19:
      return (Knock19());
    case 20:
      return (Knock20());
    case 21:
      return (Knock21());
    case 22:
      return (Knock22());
    case 23:
      return (Knock23());
    case 24:
      return (Knock24());
    case 25:
      return (Knock25());
    case 26:
      return (Knock26());
    case 27:
      return (Knock27());
    case 28:
      return (Knock28());
    case 29:
      return (Knock29());
    case 30:
      return (Knock30());
    case 31:
      return (Knock31());
    case 32:
      return (Knock32());
    case 33:
      return (Knock33());
    case 34:
      return (Knock34());
    case 35:
      return (Knock35());
    case 36:
      return (Knock36());
    case 37:
      return (Knock37());
    case 38:
      return (Knock38());
    case 39:
      return (Knock39());
    case 40:
      return (Knock40());
    case 41:
      return (Knock41());
    case 42:
      return (Knock42());
    case 43:
      return (Knock43());
    case 44:
      return (Knock44());
    case 45:
      return (Knock45());
    case 46:
      return (Knock46());
    case 47:
      return (Knock47());
    case 48:
      return (Knock48());
    case 49:
      return (Knock49());
    case 50:
      return (Knock50());
    case 51:
      return (Knock51());
    case 52:
      return (Knock52());
    case 53:
      return (Knock53());
  }
}
